# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -Wall -Wextra -Wno-unknown-pragmas -Wno-long-long -Wno-attributes -Wno-sign-compare -Wno-unused-parameter -O2 -g -DNDEBUG -fPIE -fvisibility=hidden   -march=native -pthread -std=c++11 -m64 -std=c++11

CXX_DEFINES = -DMCBOOSTER_BACKEND=CUDA -DROOT_FOUND -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP

CXX_INCLUDES = -I/home/fb/GooFit/include -I/home/fb/GooFit/build/include -I/home/fb/GooFit/extern/MCBooster -I/home/fb/GooFit/extern/generics -I/home/fb/GooFit/extern/CLI11/include -I/home/fb/GooFit/extern/FeatureDetector/src -I/home/fb/GooFit/extern/fmt/include -isystem /home/fb/GooFit/extern/thrust -isystem /usr/local/cuda/include -isystem /home/fb/root/include -isystem /home/fb/GooFit/extern/rang/include -isystem /home/fb/GooFit/extern/Eigen 

